# Generated by Django 3.1.2 on 2023-10-17 07:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('map', '0001_initial'), ('map', '0002_auto_20201020_1143'), ('map', '0003_popup'), ('map', '0004_auto_20201020_1706'), ('map', '0005_shutdownhours'), ('map', '0006_auto_20201021_1501'), ('map', '0007_remove_longestshutdowns_link'), ('map', '0008_auto_20201028_1539'), ('map', '0009_auto_20201028_1546'), ('map', '0010_shutdownsin_india_state_wise'), ('map', '0011_footer'), ('map', '0012_popup_isdisabled'), ('map', '0013_grpahs'), ('map', '0014_faqs'), ('map', '0015_networkaffected'), ('map', '0016_auto_20210709_1533'), ('map', '0017_shutdownsin_india_duration')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='networkAffectedBoth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='networkAffectedMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveShutdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReactiveShutdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShutdownDistrictWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('totalNumber', models.IntegerField()),
            ],
            options={
                'ordering': ['totalNumber'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownStateWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=80)),
                ('totalNumber', models.IntegerField()),
            ],
            options={
                'ordering': ['totalNumber'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
                ('videoLink', models.TextField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownYearsWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalNumber', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='TotalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('videoLink', models.TextField()),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='networkAffectedBroadband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShutdownHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('hoursequalto24', models.IntegerField()),
                ('hoursequalto72', models.IntegerField()),
                ('hoursmorethan72', models.IntegerField()),
                ('informationNotAvailable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LongestShutdowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('district', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('description', models.TextField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownsIn_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('shutdown_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('shutdown_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('source', models.TextField()),
                ('nature', models.CharField(max_length=15)),
                ('network_effected', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=80, null=True)),
                ('isVerified', models.BooleanField()),
                ('active', models.BooleanField()),
                ('lastModified', models.DateTimeField(auto_now=True, null=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['publishedDate'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
                ('videoLink', models.TextField()),
                ('description', models.TextField()),
                ('subdescription', models.TextField()),
                ('link', models.TextField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('isDisabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='Grpahs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('graphid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Write your faqs!')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='networkAffected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('both', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('broadband', models.IntegerField()),
                ('na', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShutdownsIn_India_In_Old_Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('shutdown_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('shutdown_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('source', models.TextField()),
                ('nature', models.CharField(max_length=15)),
                ('network_effected', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=80, null=True)),
                ('isVerified', models.BooleanField()),
                ('active', models.BooleanField()),
                ('lastModified', models.DateTimeField(auto_now=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['publishedDate'],
            },
        ),
    ]
