# Generated by Django 4.2.6 on 2024-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_squashed_0017_shutdownsin_india_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='networkAffected',
        ),
        migrations.DeleteModel(
            name='networkAffectedBoth',
        ),
        migrations.DeleteModel(
            name='networkAffectedBroadband',
        ),
        migrations.DeleteModel(
            name='networkAffectedMobile',
        ),
        migrations.DeleteModel(
            name='PreventiveShutdown',
        ),
        migrations.DeleteModel(
            name='ReactiveShutdown',
        ),
        migrations.DeleteModel(
            name='ShutdownDistrictWise',
        ),
        migrations.DeleteModel(
            name='ShutdownHours',
        ),
        migrations.DeleteModel(
            name='ShutdownsIn_India',
        ),
        migrations.DeleteModel(
            name='ShutdownStateWise',
        ),
        migrations.DeleteModel(
            name='ShutdownYearsWise',
        ),
        migrations.DeleteModel(
            name='TotalStats',
        ),
        migrations.AlterModelOptions(
            name='shutdownsin_india_in_old_way',
            options={'ordering': ['-publishedDate']},
        ),
        migrations.AlterField(
            model_name='faqs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grpahs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='longestshutdowns',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shutdownsin_india_in_old_way',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shutdownvideos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trendingvideos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
