# Generated by Django 3.1.2 on 2023-10-17 08:00

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('static_pages', '0001_initial'), ('static_pages', '0002_jnkyearwise'), ('static_pages', '0003_jnktrendingvideos_jnkyear'), ('static_pages', '0004_delete_jnkyear'), ('static_pages', '0005_jnkgraphics'), ('static_pages', '0006_jnkresearch'), ('static_pages', '0007_caagraphics_caaresearch_caatrendingvideos'), ('static_pages', '0008_auto_20201109_1620'), ('static_pages', '0009_auto_20201110_1333'), ('static_pages', '0010_auto_20201110_1434'), ('static_pages', '0011_auto_20201110_1441'), ('static_pages', '0012_auto_20201110_1444'), ('static_pages', '0013_auto_20201110_1447'), ('static_pages', '0014_auto_20201110_2049'), ('static_pages', '0015_auto_20201110_2049'), ('static_pages', '0016_auto_20201110_2053'), ('static_pages', '0017_auto_20201110_2053'), ('static_pages', '0018_auto_20201110_2054'), ('static_pages', '0019_auto_20210111_1229'), ('static_pages', '0020_auto_20210111_1610'), ('static_pages', '0021_jnkresearch_link'), ('static_pages', '0022_caaresearch_link')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lostVoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('speaker', models.TextField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Write your description here!')),
                ('youtube_url', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='JnKyearWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalNumber', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='JnKTrendingVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('videoLink', models.URLField()),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='CAAGraphics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('uploadImage', models.FileField(blank=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='CAATrendingVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('videoLink', models.URLField()),
                ('uploadThumbnail', models.FileField(blank=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='JnKGraphics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('uploadImage', models.FileField(blank=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='JnKResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(blank=True)),
                ('district', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateTimeField(blank=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
        migrations.CreateModel(
            name='CAAResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(blank=True)),
                ('district', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateTimeField(blank=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
    ]
