
Andhra_Pradesh = [" East Godavari",
   " Anantapur",
   " Chittoor",
   " Guntur",
   " Kadapa",
   " Krishna",
   " Kurnool",
   " Nellore",
   " Prakasam",
   " Srikakulam",
   " Visakhapatnam",
   " Vizianagaram",
   " West Godavari"]
  

Arunachal_Pradesh  = [" Lower Dibang Valley",
   " Dibang Valley ",
   " Anjaw",
   " Siang",
   " Changlang",
   " East Kameng",
   " East Siang",
   " Kamle",
   " Kra Daadi",
   " Kurung Kumey",
   " Lepa Rada *",
   " Lohit",
   " Longding",
   " Lower Siang",
   " Lower Subansiri",
   " Namsai",
   " Pakke Kessang *",
   " Papum Pare",
   " Shi Yomi *",
   " Tawang",
   " Tirap",
   " Upper Siang",
   " Upper Subansiri",
   " West Kameng",
   " West Siang",]

Assam  =[" Bajali",
   " Baksa",
   " Barpeta",
   " Biswanath",
   " Bongaigaon",
   " Cachar",
   " Charaideo",
   " Chirang",
   " Darrang",
   " Dhemaji",
   " Dhubri",
   " Dibrugarh",
   " Dima Hasao",
   " Goalpara",
   " Golaghat",
   " Hailakandi",
   " Hojai",
   " Jorhat",
   " Kamrup",
   " Kamrup Metropolitan",
   " Karbi Anglong",
   " Karimganj",
   " Kokrajhar",
   " Lakhimpur",
   " Majuli",
   " Morigaon",
   " Nagaon",
   " Nalbari",
   " Sivasagar",
   " Sonitpur",
   " South Salmara-Mankachar",
   " Tinsukia",
   " Udalguri",
   " West Karbi Anglong"]

Bihar =[ " Araria",
   " Arwal",
   " Aurangabad",
   " Banka",
   " Begusarai",
   " Bhagalpur",
   " Bhojpur",
   " Buxar",
   " Darbhanga",
   " East Champaran",
   " Gaya",
   " Gopalganj",
   " Jamui",
   " Jehanabad",
   " Kaimur",
   " Katihar",
   " Khagaria",
   " Kishanganj",
   " Lakhisarai",
   " Madhepura",
   " Madhubani",
   " Munger",
   " Muzaffarpur",
   " Nalanda",
   " Nawada",
   " Patna",
   " Purnia",
   " Rohtas",
   " Saharsa",
   " Samastipur",
   " Saran",
   " Sheikhpura",
   " Sheohar",
   " Sitamarhi",
   " Siwan",
   " Supaul",
   " Vaishali",
   " West Champaran"]

Chhattisgarh =[" Gaurela Pendra Marwahi",
   " Balrampur Ramanujganj",
    " Balod",
   " Baloda Bazar",
   " Bastar",
   " Bemetara",
   " Bijapur",
   " Bilaspur",
   " Dantewada",
   " Dhamtari",
   " Durg",
   " Gariaband",
   " Janjgir Champa",
   " Jashpur",
   " Kabirdham",
   " Kanker",
   " Kondagaon",
   " Korba",
   " Koriya",
   " Mahasamund",
   " Mungeli",
   " Narayanpur",
   " Raigarh",
   " Raipur",
   " Rajnandgaon",
   " Sukma",
   " Surajpur",
   " Surguja"]

Goa =[" North Goa",
   " South Goa"]

Gujarat =[ " Ahmedabad",
   " Amreli",
   " Anand",
   " Aravalli",
   " Banaskantha",
   " Bharuch",
   " Bhavnagar",
   " Botad",
   " Chhota Udaipur"
   " Dahod",
   " Dang",
   " Devbhoomi Dwarka",
   " Gandhinagar",
   " Gir Somnath",
   " Jamnagar",
   " Junagadh",
   " Kheda",
   " Kutch",
   " Mahisagar",
   " Mehsana",
   " Morbi",
   " Narmada",
   " Navsari",
   " Panchmahal",
   " Patan",
   " Porbandar",
   " Rajkot",
   " Sabarkantha",
   " Surat",
   " Surendranagar",
   " Tapi",
   " Vadodara",
   " Valsad"]

Haryana =[" Ambala",
   " Bhiwani",
   " Charkhi Dadri",
   " Faridabad",
   " Fatehabad",
   " Gurugram *",
   " Hisar",
   " Jhajjar",
   " Jind",
   " Kaithal",
   " Karnal",
   " Kurukshetra",
   " Mahendragarh",
   " Mewat",
   " Palwal",
   " Panchkula",
   " Panipat",
   " Rewari",
   " Rohtak",
   " Sirsa",
   " Sonipat",
   " Yamunanagar"]

Himachal_Pradesh = [" Bilaspur",
   " Chamba",
   " Hamirpur",
   " Kangra",
   " Kinnaur",
   " Kullu",
   " Lahaul Spiti",
   " Mandi",
   " Shimla",
   " Sirmaur",
   " Solan",
   " Una"]

Jammu_Kashmir = ["Anantnag",
   " Bandipora",
   " Baramulla",
   " Budgam",
   " Doda",
   " Ganderbal",
   " Jammu",
   " Kathua",
   " Kishtwar",
   " Kulgam",
   " Kupwara",
   " Poonch",
   " Pulwama",
   " Rajouri",
   " Ramban", 
   " Reasi",
   " Samba",
   " Shopian",
   " Srinagar",
   " Udhampur"]

Jharkhand =[" Bokaro",
   " Chatra",
   " Deoghar",
   " Dhanbad",
   " Dumka",
   " East Singhbhum",
   " Garhwa",
   " Giridih",
   " Godda",
   " Gumla",
   " Hazaribagh",
   " Jamtara",
   " Khunti",
   " Koderma",
   " Latehar",
   " Lohardaga",
   " Pakur",
   " Palamu",
   " Ramgarh",
   " Ranchi",
   " Sahebganj",
   " Seraikela Kharsawan",
   " Simdega",
   " West Singhbhum"]

Karnataka =[" Bagalkot",
   " Bangalore Rural",
   " Bangalore Urban",
   " Belgaum",
   " Bellary",
   " Bidar",
   " Chamarajanagar",
   " Chikkaballapur",
   " Chikkamagaluru",
   " Chitradurga",
   " Dakshina Kannada",
   " Davanagere",
   " Dharwad",
   " Gadag",
   " Gulbarga *",
   " Hassan",
   " Haveri",
   " Kodagu",
   " Kolar",
   " Koppal",
   " Mandya",
   " Mysore",
   " Raichur",
   " Ramanagara",
   " Shimoga",
   " Tumkur",
   " Udupi",
   " Uttara Kannada",
   " Vijayapura *",
   " Yadgir"]

Kerala =[" Alappuzha",
   " Ernakulam",
   " Idukki",
   " Kannur",
   " Kasaragod",
   " Kollam",
   " Kottayam",
   " Kozhikode",
   " Malappuram",
   " Palakkad",
   " Pathanamthitta",
   " Thiruvananthapuram",
   " Thrissur",
   " Wayanad",]

Madhya_Pradesh =[" Agar Malwa",
   " Alirajpur",
   " Anuppur",
   " Ashoknagar",
   " Balaghat",
   " Barwani",
   " Betul",
   " Bhind",
   " Bhopal",
   " Burhanpur",
   " Chachaura*",
   " Chhatarpur",
   " Chhindwara",
   " Damoh",
   " Datia",
   " Dewas",
   " Dhar",
   " Dindori",
   " Guna",
   " Gwalior",
   " Harda",
   " Hoshangabad",
   " Indore",
   " Jabalpur",
   " Jhabua",
   " Katni",
   " Khandwa",
   " Khargone",
   " Maihar*",
   " Mandla",
   " Mandsaur",
   " Morena",
   " Nagda*",
   " Narsinghpur",
   " Neemuch",
   " Niwari *",
   " Panna",
   " Raisen",
   " Rajgarh",
   " Ratlam",
   " Rewa",
   " Sagar",
   " Satna",
   " Sehore",
   " Seoni",
   " Shahdol",
   " Shajapur",
   " Sheopur",
   " Shivpuri",
   " Sidhi",
   " Singrauli",
   " Tikamgarh",
   " Ujjain",
   " Umaria",
   " Vidisha"]

Maharashtra =[" Ahmednagar",
   " Akola",
   " Amravati",
   " Aurangabad",
   " Beed",
   " Bhandara",
   " Buldhana",
   " Chandrapur",
   " Dhule",
   " Gadchiroli",
   " Gondia",
   " Hingoli",
   " Jalgaon",
   " Jalna",
   " Kolhapur",
   " Latur",
   " Mumbai City",
   " Mumbai Suburban",
   " Nagpur",
   " Nanded",
   " Nandurbar",
   " Nashik",
   " Osmanabad",
   " Palghar",
   " Parbhani",
   " Pune",
   " Raigad",
   " Ratnagiri",
   " Sangli",
   " Satara",
   " Sindhudurg",
   " Solapur",
   " Thane",
   " Wardha",
   " Washim",
   " Yavatmal"]

Manipur =[" Bishnupur",
   " Chandel",
   " Churachandpur",
   " Imphal East",
   " Imphal West",
   " Jiribam",
   " Kakching",
   " Kamjong",
   " Kangpokpi",
   " Noney",
   " Pherzawl",
   " Senapati",
   " Tamenglong",
   " Tengnoupal",
   " Thoubal",
   " Ukhrul"]

Meghalaya =[" East Garo Hills",
   " East Jaintia Hills",
   " East Khasi Hills",
   " North Garo Hills",
   " Ri Bhoi",
   " South Garo Hills",
   " South West Garo Hills",
   " South West Khasi Hills",
   " West Garo Hills",
   " West Jaintia Hills",
   " West Khasi Hills"]

Mizoram =[" Aizawl",
   " Champhai",
   " Hnahthial",
   " Khawzawl",
   " Kolasib",
   " Lawngtlai",
   " Lunglei",
   " Mamit",
   " Saiha",
   " Saitual",
   " Serchhip"]

Nagaland =[" Mon",
   " Dimapur",
   " Kiphire",
   " Kohima",
   " Longleng",
   " Mokokchung",
   " Noklak",
   " Peren",
   " Phek",
   " Tuensang",
   " Wokha",
   " Zunheboto"]

Odisha =[" Angul",
   " Balangir",
   " Balasore",
   " Bargarh",
   " Bhadrak",
   " Boudh",
   " Cuttack",
   " Debagarh",
   " Dhenkanal",
   " Gajapati",
   " Ganjam",
   " Jagatsinghpur",
   " Jajpur",
   " Jharsuguda",
   " Kalahandi",
   " Kandhamal",
   " Kendrapara",
   " Kendujhar",
   " Khordha *",
   " Koraput",
   " Malkangiri",
   " Mayurbhanj",
   " Nabarangpur",
   " Nayagarh",
   " Nuapada",
   " Puri",
   " Rayagada",
   " Sambalpur",
   " Subarnap la",
   " Ludhiana",
   " Mansa",
   " Moga",
   " Mohali",
   " Muktsar",
   " Pathankot",
   " Patiala",
   " Rupnagar",
   " Sangrur",
   " Shaheed Bhagat Singh Nagar ",
   " Tarn Taran"]

Punjab = [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Mansa",
    "Moga",
    "Mohali",
    "Muktsar",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar",
    "Tarn Taran"]

Rajasthan =[" Ajmer",
   " Alwar",
   " Banswara",
   " Baran",
   " Barmer",
   " Bharatpur",
   " Bhilwara",
   " Bikaner",
   " Bundi",
   " Chittorgarh",
   " Churu",
   " Dausa",
   " Dholpur",
   " Dungarpur",
   " Sri Ganganagar",
   " Hanumangarh",
   " Jaipur",
   " Jaisalmer",
   " Jalore",
   " Jhalawar",
   " Jhunjhunu",
   " Jodhpur",
   " Karauli",
   " Kota",
   " Nagaur",
   " Pali",
   " Pratapgarh",
   " Rajsamand",
   " Sawai Madhopur",
   " Sikar",
   " Sirohi",
   " Tonk",
   " Udaipur"]

Sikkim =[" East Sikkim",
   " North Sikkim",
   " South Sikkim",
   " West Sikkim"]

Tamil_Nadu =[" Ariyalur",
   " Chengalpattu *",
   " Chennai",
   " Coimbatore",
   " Cuddalore",
   " Dharmapuri",
   " Dindigul",
   " Erode",
   " Kallakurichi *",
   " Kanchipuram",
   " Kanyakumari",
   " Karur",
   " Krishnagiri",
   " Madurai",
   " Mayiladuthurai*",
   " Nagapattinam",
   " Namakkal",
   " Nilgiris",
   " Perambalur",
   " Pudukkottai",
   " Ramanathapuram",
   " Ranipet*",
   " Salem",
   " Sivaganga",
   " Tenkasi *",
   " Thanjavur",
   " Theni",
   " Thoothukudi",
   " Tiruchirappalli",
   " Tirunelveli",
   " Tirupattur*",
   " Tiruppur",
   " Tiruvallur",
   " Tiruvannamalai",
   " Tiruvarur",
   " Vellore",
   " Viluppuram",
   " Virudhunagar"]

Telangana  =[" Adilabad",
   " Bhadradri Kothagudem",
   " Hyderabad",
   " Jagtial",
   " Jangaon",
   " Jayashankar Bhupalpally",
   " Jogulamba Gadwal",
   " Kamareddy",
   " Karimnagar",
   " Khammam",
   " Komaram Bheem ",
   " Mulugu *",
   " Nagarkurnool",
   " Nalgonda",
   " Narayanpet *",
   " Nirmal",
   " Nizamabad",
   " Peddapalli",
   " Rajanna Sircilla",
   " Ranga Re ",
   " Vikarabad",
   " Wanaparthy",
   " Warangal Rural",
   " Warangal Urban",
   " Yadadri Bhuvanagiri"]

Tripura =[" Dhalai",
   " Gomati",
   " Khowai",
   " North Tripura",
   " Sepahijala",
   " South Tripura",
   " Unakoti",
   " West Tripura"]

Uttar_Pradesh =[ " Agra",
   " Aligarh",
   " Prayagraj*",
   " Ambedkar Nagar",
   " Amethi *",
   " Amroha *",
   " Auraiya",
   " Azamgarh",
   " Baghpat",
   " Bahraich",
   " Ballia",
   " Balrampur",
   " Banda",
   " Barabanki",
   " Bareilly",
   " Basti",
   " Bhadohi",
   " Bijnor",
   " Budaun",
   " Bulandshahr",
   " Chandauli",
   " Chitrakoot",
   " Deoria",
   " Etah",
   " Etawah",
   " Ayodhya *",
   " Farrukhabad",
   " Fatehpur",
   " Firozabad",
   " Gautam Buddha Nagar",
   " Ghaziabad",
   " Ghazipur",
   " Gonda",
   " Gorakhpur",
   " Hamirpur",
   " Hapur *",
   " Hardoi",
   " Hathras *",
   " Jalaun",
   " Jaunpur",
   " Jhansi",
   " Kannauj",
   " Kanpur Dehat *",
   " Kanpur Nagar",
   " Kasganj *",
   " Kaushambi",
   " Kheri",
   " Kushinagar",
   " Lalitpur",
   " Lucknow",
   " Maharajganj",
   " Mahoba",
   " Mainpuri",
   " Mathura",
   " Mau",
   " Meerut",
   " Mirzapur",
   " Moradabad",
   " Muzaffarnagar",
   " Pilibhit",
   " Pratapgarh",
   " Raebareli",
   " Rampur",
   " Saharanpur",
   " Sambhal *",
   " Sant Kabir Nagar",
   " Shahjahanpur",
   " Shamli *",
   " Shravasti",
   " Siddharthnagar",
   " Sitapur",
   " Sonbhadra",
   " Sultanpur",
   " Unnao",
   " Varanasi"]

Uttarakhand =[" Chamoli",
   " Champawat",
   " Dehradun",
   " Haridwar",
   " Nainital",
   " Pauri",
   " Pithoragarh",
   " Rudraprayag",
   " Tehri",
   " Udham Singh Nagar",
   " Uttarkashi"]

West_Bengal =[" Alipurduar",
   " Bankura",
   " Birbhum",
   " Cooch Behar",
   " Dakshin Dinajpur",
   " Darjeeling",
   " Hooghly",
   " Howrah",
   " Jalpaiguri",
   " Jhargram",
   " Kalimpong",
   " Kolkata",
   " Malda",
   " Murshidabad",
   " Nadia",
   " North 24 Parganas",
   " Paschim Bardhaman",
   " Paschim Medinipur",
   " Purba Bardhaman",
   " Purba Medinipur",
   " Purulia",
   " South 24 Parganas",
   " Uttar Dinajpur"]

Andaman_Nicobar =[" Nicobar",
   " North Middle Andaman",
   " South Andaman"]
Chandigarh =[" Chandigarh"]

Dadra_Nagar_Haveli =["Dadra Nagar Haveli"]

Daman_Diu =[ " Daman"," Diu"]

Delhi =[" Central Delhi",
   " East Delhi",
   " New Delhi",
   " North Delhi",
   " North East Delhi",
   " North West Delhi",
   " Shahdara",
   " South Delhi",
   " South East Delhi",
   " South West Delhi",
   " West Delhi"]

Lakshadweep =["Lakshadweep"]

Ladakh =[" Kargil"," Leh"]

Puducherry =[" Karaikal"," Mahe"," Puducherry"," Yanam"]


India=[["Andhra_Pradesh",Andhra_Pradesh],
       ["Arunachal_Pradesh",Arunachal_Pradesh],
       ["Assam"         ,Assam],
       ["Bihar"         ,Bihar],
       ["Chhattisgarh"  ,Chhattisgarh],
       ["Goa"           ,Goa],
       ["Gujarat"       ,Gujarat],
       ["Haryana"       ,Haryana],
       ["Himachal_Pradesh",Himachal_Pradesh],
       ["Jammu_Kashmir",Jammu_Kashmir],
       ["Jharkhand"     ,Jharkhand],
       ["Karnataka"     ,Karnataka],
       ["Kerala"        ,Kerala],
       ["Madhya_Pradesh",Madhya_Pradesh],
       ["Maharashtra"    ,  Maharashtra],
       ["Manipur"        ,  Manipur],
       ["Meghalaya"      ,  Meghalaya],
       ["Mizoram"        ,  Mizoram],
       ["Nagaland"       ,  Nagaland],
       ["Odisha"         ,  Odisha],
       ["Puducherry"     , Puducherry],
       ["Punjab"         ,  Punjab],
       ["Rajasthan"      ,  Rajasthan],
       ["Sikkim"         ,  Sikkim],
       ["Tamil_Nadu"     ,  Tamil_Nadu],
       ["Telangana"      ,  Telangana],
       ["Tripura"        ,  Tripura],
       ["Uttar_Pradesh"   ,  Uttar_Pradesh],
       ["Uttarakhand"    ,  Uttarakhand],
       ["West_Bengal"     ,  West_Bengal],
       ["Andaman_Nicobar",  Andaman_Nicobar]]


states_choice=[]
district_choice=[]

def StatesOfIndia():
   for state in India:
      flag_for_state=[]
      flag_for_state.append(state[0])
      flag_for_state.append(state[0])
      states_choice.append(tuple(flag_for_state))
      del(flag_for_state)
   return tuple(states_choice)


def DistrictOfStates(selected_state):
   counter=0
   for state in India:
      counter+=1
      if selected_state == state[0]:
         return district_list(counter)

def district_list(counter):
   for x in range(0,len(India)):
      if counter==x:
         for district in India[x][1]:
            flag=[]
            flag.append[district]
            flag.append[district]
            district_choice.append(tuple(flag))
            del(flag)
         return tuple(district_choice)








   
   

    








                          










